server:
  address: localhost
  port: 9999
#  ????? ??? ?? (graceful, immediate)? ?? ??
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  lifecycle:
#    ??? ?? ???? gradeful ?? ???? (?? 30s --> 1m?? ??)
    timeout-per-shutdown-phase: 1m