server:
  address: localhost
  port: 9999
#  ????? ??? ?? (graceful, immediate)? ?? ??
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  lifecycle:
#    ??? ?? ???? gradeful ?? ???? (?? 30s --> 1m?? ??)
    timeout-per-shutdown-phase: 1m
  config:
    import: classpath:additional-application.properties
app:
  sbip:
    ct:
      name: CourseTracker
      ip: 127.0.0.1
      port: 9090
      security:
        enable: true
        token: saldfksdklfsdlfkjds
        roles: USER,ADMINS
